name: C/C++ CI

on:
  push:
    branches:
      - master
      - develop
    tags:
      - "*"
  pull_request:
    branches:
      - master
      - develop

jobs:
  RALibretro-Win64:
    runs-on: windows-2019
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install MSBuild
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Install Windows SDK 8.1
      run: choco install windows-sdk-8.1
    - name: Build
      run: msbuild.exe RALibretro.sln -p:Configuration=Release -p:Platform=x64

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: RALibretro
        path: bin64
